// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1570130293);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1570130413);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1570208022);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1570130173);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1570204838);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1570130653);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1570130533);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{12336a12-f061-4312-be52-ee0e0fd4322b}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1570147200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1570206177);
user_pref("browser.onboarding.notification.prompt-count", 2);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1570207998581");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1570211598581");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190505111237");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1570205683");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1570129783692");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.6.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Wed, 02 Oct 2019 21:54:30 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1570130294);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190505111237");
user_pref("extensions.lastAppVersion", "60.6.2");
user_pref("extensions.lastPlatformVersion", "60.6.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signer.hotfixed", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"7e823678-389d-427f-aa94-b4de827aaa42\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1570130600);
user_pref("media.gmp-manager.buildID", "20190505111237");
user_pref("media.gmp-manager.lastCheck", 1570130209);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1570130600);
user_pref("places.history.expiration.transient_current_max_pages", 55400);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "720d54ba-b131-4e5e-8597-6bd1e25bca5a");
user_pref("services.blocklist.addons.checked", 1570110608);
user_pref("services.blocklist.clock_skew_seconds", 19805);
user_pref("services.blocklist.gfx.checked", 1570110608);
user_pref("services.blocklist.last_etag", "\"1570060826650\"");
user_pref("services.blocklist.last_update_seconds", 1570110608);
user_pref("services.blocklist.onecrl.checked", 1570110608);
user_pref("services.blocklist.pinning.checked", 1570110608);
user_pref("services.blocklist.plugins.checked", 1570110608);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1570130600);
user_pref("toolkit.startup.last_success", 1570205681);
user_pref("toolkit.telemetry.cachedClientID", "75951509-b0a6-4b95-bf54-05e1ca9d9881");
user_pref("toolkit.telemetry.previousBuildID", "20190505111237");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
